### ISSUE TITLE
Installation of missing dependancies

### ISSUE THREAD

**Issue by tpoindessous** [martezr/inspec-gcp#4]
Hi

I tried your example and I got an error because my computer didn't have the google api ruby librairies.

I needed to do a `bundle install` on your project's directory.

Thanks.

```
/Users/thomas/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- google/apis (LoadError)
	from /Users/thomas/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/dsl_shared.rb:14:in `require'
	from libraries/gcp_connection.rb:3:in `load_with_context'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/profile_context.rb:157:in `instance_eval'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/profile_context.rb:157:in `load_with_context'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/profile_context.rb:146:in `load_library_file'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/profile_context.rb:133:in `block in load_libraries'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/profile_context.rb:131:in `each'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/profile_context.rb:131:in `load_libraries'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/profile.rb:194:in `load_libraries'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/profile.rb:186:in `block in load_libraries'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/dependencies/dependency_set.rb:65:in `block in each'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/dependencies/dependency_set.rb:64:in `each'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/dependencies/dependency_set.rb:64:in `each'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/profile.rb:185:in `load_libraries'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/runner.rb:86:in `block in load'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/runner.rb:82:in `each'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/runner.rb:82:in `load'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/runner.rb:103:in `run'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/lib/inspec/cli.rb:168:in `exec'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/gems/inspec-2.0.17/bin/inspec:12:in `<top (required)>'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/bin/inspec:23:in `load'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/bin/inspec:23:in `<main>'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/thomas/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by martezr** [comment]
@tpoindessous At this point there's not much that can be done about this other than updating the readme with the project as at this point it isn't a packaged gem that would handle the dependency installation.
